repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --config ./.black
        language: python3.12.4
        types: [python]

      - id: flake8
        name: flake8
        entry: flake8 --config .flake8
        language: python3.12.4
        types: [python]